<?php

namespace Database\Seeders;

use App\Models\Movie;
use App\Models\Tag;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [
            [
                'title' => 'Saving Private Ryan',
                'release_year' => 1998,
                'release_date' => '1998-07-24',
                'synopsis' => 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
                'runtime' => 169,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=zwhP5b4tD6g',
                'imdb_id' => 'tt0120815',
                'tags' => ['Drama', 'Action', 'WWII', 'Combat', 'Sacrifice'],
            ],
            [
                'title' => '1917',
                'release_year' => 2019,
                'release_date' => '2019-12-25',
                'synopsis' => 'Two British soldiers are given a seemingly impossible mission to deliver a message deep in enemy territory that will stop 1,600 men from walking straight into a deadly trap.',
                'runtime' => 119,
                'country' => 'UK',
                'conflict' => 'WWI',
                'trailer_url' => 'https://www.youtube.com/watch?v=YqNYrYUiMfg',
                'imdb_id' => 'tt8579674',
                'tags' => ['Drama', 'Action', 'WWI', 'Combat', 'Heroism'],
            ],
            [
                'title' => 'Apocalypse Now',
                'release_year' => 1979,
                'release_date' => '1979-08-15',
                'synopsis' => 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.',
                'runtime' => 147,
                'country' => 'USA',
                'conflict' => 'Vietnam War',
                'trailer_url' => 'https://www.youtube.com/watch?v=FTjG-Aux_yg',
                'imdb_id' => 'tt0078788',
                'tags' => ['Drama', 'Vietnam War', 'Anti-war', 'Combat'],
            ],
            [
                'title' => 'Dunkirk',
                'release_year' => 2017,
                'release_date' => '2017-07-21',
                'synopsis' => 'Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.',
                'runtime' => 106,
                'country' => 'UK',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=F-eMt3SrfFU',
                'imdb_id' => 'tt5013056',
                'tags' => ['Drama', 'Action', 'WWII', 'Survival', 'Historical'],
            ],
            [
                'title' => 'Full Metal Jacket',
                'release_year' => 1987,
                'release_date' => '1987-06-26',
                'synopsis' => 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.',
                'runtime' => 116,
                'country' => 'USA',
                'conflict' => 'Vietnam War',
                'trailer_url' => 'https://www.youtube.com/watch?v=x7DUn_XdWDk',
                'imdb_id' => 'tt0093058',
                'tags' => ['Drama', 'Vietnam War', 'Anti-war', 'Combat'],
            ],
            [
                'title' => 'Hacksaw Ridge',
                'release_year' => 2016,
                'release_date' => '2016-11-04',
                'synopsis' => 'World War II American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.',
                'runtime' => 139,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=s2-1hz1juBI',
                'imdb_id' => 'tt2119532',
                'tags' => ['Drama', 'Biography', 'WWII', 'Heroism', 'Combat'],
            ],
            [
                'title' => 'Platoon',
                'release_year' => 1986,
                'release_date' => '1986-12-19',
                'synopsis' => 'Chris Taylor, a young recruit in Vietnam, faces a moral crisis when confronted with the horrors of war and the duality of man.',
                'runtime' => 120,
                'country' => 'USA',
                'conflict' => 'Vietnam War',
                'trailer_url' => 'https://www.youtube.com/watch?v=aNUr__-VZeQ',
                'imdb_id' => 'tt0091763',
                'tags' => ['Drama', 'Vietnam War', 'Anti-war', 'Combat'],
            ],
            [
                'title' => 'Schindler\'s List',
                'release_year' => 1993,
                'release_date' => '1993-12-15',
                'synopsis' => 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
                'runtime' => 195,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=gG22XNhtnoY',
                'imdb_id' => 'tt0108052',
                'tags' => ['Drama', 'Biography', 'Historical', 'WWII', 'Resistance'],
            ],
            [
                'title' => 'Black Hawk Down',
                'release_year' => 2001,
                'release_date' => '2001-12-28',
                'synopsis' => '160 elite U.S. soldiers drop into Somalia to capture two top lieutenants of a renegade warlord and find themselves in a desperate battle with a large force of heavily armed Somalis.',
                'runtime' => 144,
                'country' => 'USA',
                'conflict' => 'Somalia',
                'trailer_url' => 'https://www.youtube.com/watch?v=BUI_TaST4M0',
                'imdb_id' => 'tt0265086',
                'tags' => ['Drama', 'Action', 'Historical', 'Combat', 'Survival'],
            ],
            [
                'title' => 'The Thin Red Line',
                'release_year' => 1998,
                'release_date' => '1998-12-23',
                'synopsis' => 'Adaptation of James Jones\' autobiographical 1962 novel, focusing on the conflict at Guadalcanal during the second World War.',
                'runtime' => 170,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=mK4XhR0hkkI',
                'imdb_id' => 'tt0120863',
                'tags' => ['Drama', 'WWII', 'Anti-war', 'Combat'],
            ],
            [
                'title' => 'Das Boot',
                'release_year' => 1981,
                'release_date' => '1981-09-17',
                'synopsis' => 'A German U-boat stalks the frigid waters of the North Atlantic as its young crew experience the sheer terror and claustrophobic life of a submariner in World War II.',
                'runtime' => 149,
                'country' => 'Germany',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=aSsm04cA7hE',
                'imdb_id' => 'tt0082096',
                'tags' => ['Drama', 'WWII', 'Combat', 'Survival'],
            ],
            [
                'title' => 'American Sniper',
                'release_year' => 2014,
                'release_date' => '2014-12-25',
                'synopsis' => 'Navy S.E.A.L. sniper Chris Kyle\'s pinpoint accuracy saves countless lives on the battlefield and turns him into a legend.',
                'runtime' => 133,
                'country' => 'USA',
                'conflict' => 'Iraq War',
                'trailer_url' => 'https://www.youtube.com/watch?v=99k3u9ay1gs',
                'imdb_id' => 'tt2179136',
                'tags' => ['Biography', 'Drama', 'Iraq War', 'Combat'],
            ],
            [
                'title' => 'The Hurt Locker',
                'release_year' => 2008,
                'release_date' => '2008-10-10',
                'synopsis' => 'During the Iraq War, a Sergeant recently assigned to an army bomb squad is put at odds with his squad mates due to his maverick way of handling his work.',
                'runtime' => 131,
                'country' => 'USA',
                'conflict' => 'Iraq War',
                'trailer_url' => 'https://www.youtube.com/watch?v=2GxSDZc8etg',
                'imdb_id' => 'tt0887912',
                'tags' => ['Drama', 'Thriller', 'Iraq War', 'Combat'],
            ],
            [
                'title' => 'Paths of Glory',
                'release_year' => 1957,
                'release_date' => '1957-12-25',
                'synopsis' => 'After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.',
                'runtime' => 88,
                'country' => 'USA',
                'conflict' => 'WWI',
                'trailer_url' => 'https://www.youtube.com/watch?v=nmBDdP_Z6hA',
                'imdb_id' => 'tt0050825',
                'tags' => ['Drama', 'WWI', 'Anti-war', 'Historical'],
            ],
            [
                'title' => 'Letters from Iwo Jima',
                'release_year' => 2006,
                'release_date' => '2006-12-20',
                'synopsis' => 'The story of the battle of Iwo Jima between the United States and Imperial Japan during World War II, as told from the perspective of the Japanese who fought it.',
                'runtime' => 141,
                'country' => 'Japan',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=rrZk2V6sKpE',
                'imdb_id' => 'tt0498380',
                'tags' => ['Drama', 'WWII', 'Combat', 'Historical'],
            ],
            [
                'title' => 'The Bridge on the River Kwai',
                'release_year' => 1957,
                'release_date' => '1957-10-02',
                'synopsis' => 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors, not knowing that the allied forces are planning to destroy it.',
                'runtime' => 161,
                'country' => 'UK',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=xA5WHeRdZ00',
                'imdb_id' => 'tt0050212',
                'tags' => ['Drama', 'WWII', 'Prisoner of War', 'Historical'],
            ],
            [
                'title' => 'Come and See',
                'release_year' => 1985,
                'release_date' => '1985-10-17',
                'synopsis' => 'After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.',
                'runtime' => 142,
                'country' => 'Russia',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=UkkJZweYaLI',
                'imdb_id' => 'tt0091251',
                'tags' => ['Drama', 'WWII', 'Anti-war', 'Historical'],
            ],
            [
                'title' => 'Inglourious Basterds',
                'release_year' => 2009,
                'release_date' => '2009-08-21',
                'synopsis' => 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.',
                'runtime' => 153,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=KnrRy6kSFF0',
                'imdb_id' => 'tt0361748',
                'tags' => ['Drama', 'Action', 'WWII', 'Resistance'],
            ],
            [
                'title' => 'All Quiet on the Western Front',
                'release_year' => 2022,
                'release_date' => '2022-10-28',
                'synopsis' => 'A young German soldier\'s terrifying experiences and distress on the western front during World War I.',
                'runtime' => 148,
                'country' => 'Germany',
                'conflict' => 'WWI',
                'trailer_url' => 'https://www.youtube.com/watch?v=hf8EYbVxtCY',
                'imdb_id' => 'tt1016150',
                'tags' => ['Drama', 'WWI', 'Anti-war', 'Combat'],
            ],
            [
                'title' => 'Fury',
                'release_year' => 2014,
                'release_date' => '2014-10-17',
                'synopsis' => 'A grizzled tank commander makes tough decisions as he and his crew fight their way across Germany in April 1945.',
                'runtime' => 134,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=q94n3eWOWXM',
                'imdb_id' => 'tt2713180',
                'tags' => ['Drama', 'Action', 'WWII', 'Combat', 'Leadership'],
            ],
            [
                'title' => 'The Great Escape',
                'release_year' => 1963,
                'release_date' => '1963-07-04',
                'synopsis' => 'Allied prisoners of war plan for several hundred of their number to escape from a German camp during World War II.',
                'runtime' => 172,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=MfRi3v1ym3w',
                'imdb_id' => 'tt0057115',
                'tags' => ['Drama', 'WWII', 'Prisoner of War', 'Historical'],
            ],
            [
                'title' => 'Lone Survivor',
                'release_year' => 2013,
                'release_date' => '2013-12-25',
                'synopsis' => 'Marcus Luttrell and his team set out on a mission to capture or kill notorious Taliban leader Ahmad Shah, in late June 2005. Marcus and his team are left to fight for their lives in one of the most valiant efforts of modern warfare.',
                'runtime' => 121,
                'country' => 'USA',
                'conflict' => 'Afghanistan War',
                'trailer_url' => 'https://www.youtube.com/watch?v=yoLFk4JK_RM',
                'imdb_id' => 'tt1091191',
                'tags' => ['Biography', 'Drama', 'Action', 'Afghanistan War', 'Survival'],
            ],
            [
                'title' => 'Zero Dark Thirty',
                'release_year' => 2012,
                'release_date' => '2012-12-19',
                'synopsis' => 'A chronicle of the decade-long hunt for al-Qaeda terrorist leader Osama bin Laden after the September 2001 attacks, and his death at the hands of the Navy S.E.A.L.s Team 6 in May 2011.',
                'runtime' => 157,
                'country' => 'USA',
                'conflict' => 'Afghanistan War',
                'trailer_url' => 'https://www.youtube.com/watch?v=j-2ZxldMO-M',
                'imdb_id' => 'tt1790885',
                'tags' => ['Drama', 'Thriller', 'Historical', 'Afghanistan War'],
            ],
            [
                'title' => 'The Pianist',
                'release_year' => 2002,
                'release_date' => '2002-09-25',
                'synopsis' => 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.',
                'runtime' => 150,
                'country' => 'France',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=BFwGqLa_oAo',
                'imdb_id' => 'tt0253474',
                'tags' => ['Biography', 'Drama', 'WWII', 'Survival', 'Historical'],
            ],
            [
                'title' => 'Midway',
                'release_year' => 2019,
                'release_date' => '2019-11-08',
                'synopsis' => 'The story of the Battle of Midway, told by the leaders and the sailors who fought it.',
                'runtime' => 138,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=AI7U_jXDXEY',
                'imdb_id' => 'tt6924650',
                'tags' => ['Action', 'Drama', 'WWII', 'Historical', 'Combat'],
            ],
            [
                'title' => 'We Were Soldiers',
                'release_year' => 2002,
                'release_date' => '2002-03-01',
                'synopsis' => 'The story of the first major battle of the American phase of the Vietnam War, and the soldiers on both sides that fought it, while their wives wait nervously and anxiously at home for the good news or the bad news.',
                'runtime' => 138,
                'country' => 'USA',
                'conflict' => 'Vietnam War',
                'trailer_url' => 'https://www.youtube.com/watch?v=j5LPJYPxfRs',
                'imdb_id' => 'tt0277434',
                'tags' => ['Action', 'Drama', 'Vietnam War', 'Combat', 'Leadership'],
            ],
            [
                'title' => 'The Deer Hunter',
                'release_year' => 1978,
                'release_date' => '1978-12-08',
                'synopsis' => 'An in-depth examination of the ways in which the Vietnam War impacts and disrupts the lives of several friends in a small steel mill town in Pennsylvania.',
                'runtime' => 183,
                'country' => 'USA',
                'conflict' => 'Vietnam War',
                'trailer_url' => 'https://www.youtube.com/watch?v=YU_7y8hBh-I',
                'imdb_id' => 'tt0077416',
                'tags' => ['Drama', 'Vietnam War', 'Anti-war', 'Prisoner of War'],
            ],
            [
                'title' => 'Jarhead',
                'release_year' => 2005,
                'release_date' => '2005-11-04',
                'synopsis' => 'A psychological study of Marine\'s state of mind during the Gulf War. Told through the eyes of a U.S. Marine sniper who struggles to cope with boredom, a sense of isolation, and other issues back home.',
                'runtime' => 125,
                'country' => 'USA',
                'conflict' => 'Gulf War',
                'trailer_url' => 'https://www.youtube.com/watch?v=LXLqxSB2YXA',
                'imdb_id' => 'tt0418763',
                'tags' => ['Biography', 'Drama', 'Gulf War', 'Combat'],
            ],
            [
                'title' => 'Three Kings',
                'release_year' => 1999,
                'release_date' => '1999-10-01',
                'synopsis' => 'In the aftermath of the Persian Gulf War, four soldiers set out to steal gold that was stolen from Kuwait, but they discover people who desperately need their help.',
                'runtime' => 114,
                'country' => 'USA',
                'conflict' => 'Gulf War',
                'trailer_url' => 'https://www.youtube.com/watch?v=LcAj36ZLgqQ',
                'imdb_id' => 'tt0120188',
                'tags' => ['Action', 'Drama', 'Gulf War', 'Combat'],
            ],
            [
                'title' => 'The Longest Day',
                'release_year' => 1962,
                'release_date' => '1962-10-04',
                'synopsis' => 'The events of D-Day, told on a grand scale from both the Allied and German points of view.',
                'runtime' => 178,
                'country' => 'USA',
                'conflict' => 'WWII',
                'trailer_url' => 'https://www.youtube.com/watch?v=Kv7v7foCTLw',
                'imdb_id' => 'tt0056197',
                'tags' => ['Drama', 'Action', 'WWII', 'Historical', 'Combat'],
            ],
        ];

        foreach ($movies as $movieData) {
            $tagNames = $movieData['tags'];
            unset($movieData['tags']);

            $movie = Movie::create($movieData);

            $tags = Tag::whereIn('name', $tagNames)->get();
            $movie->tags()->attach($tags);
        }
    }
}
