[program:movies-of-war-ssr]
process_name=%(program_name)s
command=php /home/deployer/movies-of-war.com/current/artisan inertia:start-ssr
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deployer
numprocs=1
redirect_stderr=true
stdout_logfile=/home/deployer/movies-of-war.com/shared/storage/logs/ssr.log
stopwaitsecs=60
