name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install Deployer
        run: |
          curl -LO https://deployer.org/deployer.phar
          chmod +x deployer.phar
          sudo mv deployer.phar /usr/local/bin/dep

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H movies-of-war.com >> ~/.ssh/known_hosts
          cat <<EOF > ~/.ssh/config
          Host movies-of-war.com
            User deployer
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Deploy
        run: dep deploy -vvv
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
